import{i as c,S as F,a as b}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC";function f(e){const t=e.map(({largeImageURL:n,webformatURL:i,tags:o,likes:r,views:a,comments:y,downloads:L})=>`<li class='gallery-item'>
             <a class='gallery-link' href='${n}'>
               <img class='gallery-image' src='${i}' alt='${o}'/>
             </a>
             <div class='container-app'>
              <p><span>Likes</span> ${r}</p>
              <p><span>Views</span> ${a}</p>
              <p><span>Comments</span> ${y}</p>
              <p><span>Downloads</span> ${L}</p>
             </div>
            </li>`).join("");s.list.insertAdjacentHTML("beforeend",t)}function w(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function B(e){e.length===0&&c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function P(e,t){Math.ceil(e/t)>1&&s.loadButton.classList.remove("hidden")}function E(e,t,n){const i=Math.ceil(t/n);e>=i?(g.observe(s.list.lastChild),s.loadButton.classList.add("hidden")):g.unobserve(s.list.lastChild)}const g=new IntersectionObserver(C);function C(e,t){e.forEach(n=>{n.isIntersecting&&c.error({position:"topRight",messageColor:"#FFF",color:"#EF4040",iconUrl:l,message:"We're sorry, but you've reached the end of search results"})})}let m=new F(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});function h(){m.on("show.simpleLightbox"),m.refresh()}const s={form:document.querySelector("form"),list:document.querySelector(".gallery"),spanLoader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button"),input:document.querySelector(".form-input")};let u=1,d="",p=15;async function A(){s.spanLoader.classList.remove("hidden");const e=await b.get("https://pixabay.com/api/",{params:{key:"31960717-8c82352157f13e8057b3011e3",q:`${d}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:p,page:u}}),{hits:t,totalHits:n}=e.data;return s.spanLoader.classList.add("hidden"),{hits:t,totalHits:n}}s.loadButton.addEventListener("click",v);s.form.addEventListener("submit",S);async function S(e){if(e.preventDefault(),d=s.input.value.trim(),s.list.innerHTML="",s.loadButton.classList.add("hidden"),d==="")return c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});u=1;try{const{hits:t,totalHits:n}=await A();B(t),f(t),P(n,p)}catch(t){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${t}`})}h(),s.form.reset()}async function v(){u++;try{const{hits:e,totalHits:t}=await A();f(e),E(u,t,p)}catch(e){console.log(e),c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${e}`})}w(),h()}
//# sourceMappingURL=commonHelpers.js.map
